log:
  level: "INFO"
storage:
  #type: "sql"
  type: "in-memory"
db:
  name: "calendar"
  host: "localhost"
  user: "postgres"
  password: "postgres"
server:
  host: "0.0.0.0"
  port: "8081"
debugMessage: "debug message test"
some: "some2"